### ISSUE TITLE
列表项，怎么默认关闭的啊

### ISSUE THREAD

**Issue by tomorrowNicest** [RoarRain/react-native-SectionList#1]
列表项，怎么默认关闭的啊
![13e16321-8827-48b1-a77f-c8071b7b0375](https://user-images.githubusercontent.com/34731610/50721187-4a88f680-10f6-11e9-9aaf-f57b2b684eb7.png)

**Comment by RoarRain** [comment]
您好，设置 section 的show为false就可以了
